version: "2"
services:
  server:
    image: f105a53/search-web:server
    build:
      context: .
      dockerfile: Server/Dockerfile
    labels:
      traefik.frontend.rule: "Host: search.j2ghz.com"
      traefik.enable: "true"
      traefik.port: "80"
    environment:
      RABBITMQ_CSTRING: "host=rabbitmq;username=guest1;password=guest1"
    depends_on:
      - rabbitmq
      - search-node
      - preview-service

  public-api:
    image: f105a53/search-web:public-api
    build:
      context: .
      dockerfile: PublicAPI/Dockerfile
    labels:
      traefik.frontend.rule: "Host: search-api.j2ghz.com"
      traefik.enable: "true"
      traefik.port: "80"
    environment:
      RABBITMQ_CSTRING: "host=rabbitmq;username=guest1;password=guest1"
    depends_on:
      - rabbitmq
      - search-node
      - preview-service

  search-node:
    image: f105a53/search-web:search-node
    build:
      context: .
      dockerfile: SearchNode/Dockerfile
    volumes:
      - "./lucene-index:/app/lucene-index"
    environment:
      RABBITMQ_CSTRING: "host=rabbitmq;username=guest1;password=guest1"
    depends_on:
      - rabbitmq

  preview-service:
    image: f105a53/search-web:preview-service
    build:
      context: .
      dockerfile: PreviewService/Dockerfile
    volumes:
      - "/mnt/zpool1/media/ipfs-export/maildir:/mnt/zpool1/media/ipfs-export/maildir:ro"
    environment:
      RABBITMQ_CSTRING: "host=rabbitmq;username=guest1;password=guest1"
    depends_on:
      - rabbitmq

  spell-check-service:
    image: f105a53/search-web:spell-check-service
    build:
      context: .
      dockerfile: SpellCheckService/Dockerfile
    volumes:
      - "./lucene-index:/app/lucene-index"
    environment:
      RABBITMQ_CSTRING: "host=rabbitmq;username=guest1;password=guest1"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
    - "15672:15672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
      
volumes:
  rabbitmq:
