version: "2"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.Server
    labels:
      traefik.frontend.rule: "Host: search.j2ghz.com"
      traefik.enable: "true"
      traefik.port: "80"
  search-api:
    build:
      context: .
      dockerfile: Dockerfile.SearchAPI
    volumes:
      - "./lucene-index:/app/lucene-index"
