version: "2"
services:
  server:
    build:
      context: .
      dockerfile: Server/Dockerfile
    labels:
      traefik.frontend.rule: "Host: search.j2ghz.com"
      traefik.enable: "true"
      traefik.port: "80"
    environment:
      - RABBITMQ_CSTRING=host=localhost;username=guest1;password=guest1
  search-node:
    build:
      context: .
      dockerfile: SearchNode/Dockerfile
    volumes:
      - "./lucene-index:/app/lucene-index"
    environment:
      - RABBITMQ_CSTRING=host=localhost;username=guest1;password=guest1
  preview-service:
    build:
      context: .
      dockerfile: PreviewService/Dockerfile
    volumes:
      - "./lucene-index:/app/lucene-index"
      - "/mnt/zpool1/media/ipfs-export/maildir:/mnt/zpool1/media/ipfs-export/maildir:ro"
    environment:
      - RABBITMQ_CSTRING=host=localhost;username=guest1;password=guest1
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
    - "15672:15672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
volumes:
  rabbitmq:
